"""A runnable stack for converted code.

A zip of DAG files is reviewable but not testable: nothing in it starts, so QA Mind
can only check the files structurally. Shipping a compose stack alongside them closes
the last step of the migration story — convert, download, *run it and test it*.

Deliberately declarative and per-target, like `profiles.py`: a new target adds an
entry here and gets a runnable output, without the converter learning anything about
Airflow. Anything with no entry simply ships without a stack, which is what every
target does today.

The stacks below are sized for a laptop and a demo — one container, SQLite,
LocalExecutor, no Redis or worker fleet. That is a deliberate trade: a production
Airflow deployment is not what a reviewer needs to answer "do these DAGs load".
"""
from __future__ import annotations

from dataclasses import dataclass, field


@dataclass(frozen=True)
class Runtime:
    """How to start converted output, and how to know it is up."""
    target: str
    #: filename -> content. Written into the zip beside the generated code.
    files: dict[str, str] = field(default_factory=dict)
    #: Where the application answers once it has started.
    port: int = 8080
    #: A path that returns 2xx when the stack is ready to be tested.
    health_path: str = "/health"
    #: How long it may take. Airflow initialises a database on first boot.
    start_timeout_s: int = 300
    notes: str = ""


_AIRFLOW_COMPOSE = """# Generated by Aura so the converted DAGs can actually be run.
#
# One container, SQLite and LocalExecutor — enough to load the DAGs, see them in the
# UI and trigger one. NOT a production deployment: no Redis, no separate scheduler,
# no worker fleet. Replace this before you deploy anything.
services:
  airflow:
    image: apache/airflow:2.9.3-python3.11
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: sqlite:////opt/airflow/airflow.db
      AIRFLOW__CORE__DAGS_FOLDER: /opt/airflow/dags
      AIRFLOW__API__AUTH_BACKENDS: airflow.api.auth.backend.session,airflow.api.auth.backend.basic_auth
      # Aura's test runner authenticates as this account. Change it for anything
      # that is not a laptop.
      _AIRFLOW_WWW_USER_USERNAME: aura
      _AIRFLOW_WWW_USER_PASSWORD: aura
      PYTHONPATH: /opt/airflow/plugins
    ports:
      - "8080:8080"
    volumes:
      - ./dags:/opt/airflow/dags
      - ./plugins:/opt/airflow/plugins
      - ./config:/opt/airflow/config
    command: >
      bash -c "airflow db migrate &&
               airflow users create --username aura --password aura
                 --firstname Aura --lastname QA --role Admin --email qa@example.com
                 || true &&
               airflow standalone"
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8080/health"]
      interval: 10s
      timeout: 5s
      retries: 30
      start_period: 60s
"""

_AIRFLOW_README = """# Running the converted DAGs

```bash
docker compose up          # or: podman compose up
open http://localhost:8080 # sign in with aura / aura
```

The first boot initialises the database and takes a few minutes.

This stack exists so the output can be *tested*, not deployed. It is one container on
SQLite with the LocalExecutor — fine for loading DAGs and triggering one by hand, and
not fine for anything else. What to change before a real deployment:

- a real database (Postgres) and executor (Celery or Kubernetes)
- a scheduler separate from the webserver
- credentials that are not `aura` / `aura`
- the connections and variables each DAG expects — see MIGRATION.md

## Testing it with Aura

QualityMind starts this stack itself and checks that every DAG loads with no import
errors. `docker compose up` by hand does the same thing more slowly.
"""

RUNTIMES: dict[str, Runtime] = {
    "airflow": Runtime(
        target="airflow",
        files={
            "docker-compose.yml": _AIRFLOW_COMPOSE,
            "RUNNING.md": _AIRFLOW_README,
            # Airflow refuses to start if its DAGs folder does not exist, and an empty
            # directory does not survive a zip.
            "plugins/.gitkeep": "",
            "config/.gitkeep": "",
        },
        port=8080,
        health_path="/health",
        start_timeout_s=300,
        notes="One container, SQLite, LocalExecutor. Sign in with aura / aura.",
    ),
}


def for_target(target: str) -> Runtime | None:
    """The runnable stack for a target, or None when there is not one.

    None is the normal case — most targets ship as code only — and callers treat it
    as "no stack", never as an error.
    """
    return RUNTIMES.get((target or "").strip().lower())
